version: '3.9'
services:
  server:
    env_file: .env
    build: ./server
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - ./server/src:/usr/server/src
    depends_on:
      - sql-server

  web:
    build: ./web
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./web/src:/usr/web/src
      - ./web/public:/usr/web/public
    environment:
      PORT: 3000
      CHOKIDAR_USEPOLLING: 1
      CHOKIDAR_POLLINTERVAL: 3000

  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'Password1'
      ACCEPT_EULA: 'Y'
